#!/bin/bash
# specify the database in ovs/ovn command 
#set -o xtrace

if [ -z "$OVS_DB_IP" ]; then 
    cat <<EOF
Warning: No enviroment variable: OVS_DB_IP
Ctrl-c to "export OVS_DB_IP=10.11.59.40", Or input it now: 
EOF
    sleep 10
    read OVS_DB_IP
fi
alias ovs-vsctl-r="ovs-vsctl --db=tcp:$OVS_DB_IP:6640 "
alias ovn-nbctl-r="ovn-nbctl --db=tcp:$OVS_DB_IP:6641 "
alias ovn-sbctl-r="ovn-sbctl --db=tcp:$OVS_DB_IP:6642 "
alias ovn-trace-r="ovn-trace --db=tcp:$OVS_DB_IP:6642 "
